on: push

name: Bump Version

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install conventional-changelog-cli"
        run: "npm install --global conventional-changelog-cli@2.x.x"
      - uses: paulhatch/semantic-version@v4.0.2
        id: semantic-version
        with:
          tag_prefix: "v"
          major_pattern: "!:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}"
      - name: Update modinfo.lua version
        run: |
          sed 's/version = ".*\..*\..*"/version = "${{ steps.semantic-version.outputs.version }}"/' modinfo.lua -i
      - name: Update CHANGELOG.md
        run: "conventional-changelog -p angular -i CHANGELOG.md -s"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(release): ${{ steps.semantic-version.outputs.version_tag }}"
          title: Bump version
          branch: github-action-bump-version
