on:
  push:
    branches:
      - new-master

name: releases
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v4.0.2
        id: semantic-version
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "!:"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "feat:"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}-prerelease${increment}"
          bump_each_commit: false
      - name: Create Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          echo git tag -a v${{ steps.semantic-version.outputs.version }} -m ""
          echo git push origin --tags
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v${{ steps.semantic-version.outputs.version }}
